config/routes.rb
R20130213Books::Application.routes.draw do
  resources :books, :authors

  root :to => 'authors#index'
end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  dob            :date
#  place_of_birth :string(255)
#  dod            :date
#  place_of_death :string(255)
#  image          :text
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Author < ActiveRecord::Base
  attr_accessible :name, :dob, :place_of_birth, :dod, :place_of_death, :image
  has_many :books
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  year       :string(255)
#  genre      :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  author_id  :integer
#

class Book < ActiveRecord::Base
  attr_accessible :title, :year, :genre, :image, :author_id
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.find(:all, :order => 'name')
  end
  def new
    @author = Author.new
  end
  def create
    author = Author.create(params[:author])
    redirect_to(author)
  end
  def show
    @author = Author.find(params[:id])
  end
  def edit
    @author = Author.find(params[:id])
  end
  def update
    author = Author.find(params[:id])
    author.update_attributes(params[:author])
    redirect_to(author)
  end
  def destroy
    author = Author.find(params[:id])
    author.delete
    redirect_to(authors_path)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order(:year)
  end
  def new
    @book = Book.new
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
  <%= f.text_field :name %>
  <%= f.label :name %><br>
  <%= f.text_field :dob %>
  <%= f.label :dob, 'Date of birth' %><br>
  <%= f.text_field :place_of_birth %>
  <%= f.label :place_of_birth %><br>
  <%= f.text_field :dod %>
  <%= f.label :dod, 'Date of death' %><br>
  <%= f.text_field :place_of_death %>
  <%= f.label :place_of_death %><br>
  <%= f.text_field :image %>
  <%= f.label :image %><br>
  <%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<div class='form'>
<h1>Edit Author</h1>
<%= render :partial => 'form' %>
</div>

app/views/authors/index.html.erb
<div class = 'blanket'>
  <% @authors.each do |author| %>
    <div class='wrap'>
    <%= link_to image_tag(author.image, :class => 'index'), author %>
    <ul>
      <li><%= author.name %></li>
      <li><%= author.dob.strftime("Born %b %d, %Y") %></li>
      <li><%= author.place_of_birth %></li>
      <% if author.dod != nil %>
      <li><%= author.dod.strftime("Died %b %d, %Y") %></li>
      <li><%= author.place_of_death %></li>
      <% end %>
    </ul>
    </div>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class='form'>
<h1>New Author</h1>
<%= render :partial => 'form' %>
</div>

app/views/authors/show.html.erb
<section>
  <%= image_tag @author.image, :class => 'show' %>
  <ul>
    <li><%= @author.name %></li>
    <li><%= @author.dob.strftime("Born %b %d, %Y") %></li>
    <li><%= @author.place_of_birth %></li>
    <% if @author.dod != nil %>
    <br>
    <li><%= @author.dod.strftime("Died %b %d, %Y") %></li>
    <li><%= @author.place_of_death %></li>
    <% end %>
  </ul>
</section>

<div class='links'>
<%= link_to 'Delete', @author, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_author_path(@author) %>
</div>

<% @author.books.order(:year).each do |book| %>
<ul>
  <li><%= link_to image_tag(book.image, :class =>'thumbnail'), book %></li>
</ul>
<% end %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= f.select :author_id, Author.all.map{|author| [author.name, author.id]}, :include_blank => true, :prompt => "Pick Author" %><br>
  <%= f.text_field :title %>
  <%= f.label :title %><br>
  <%= f.text_field :year %>
  <%= f.label :year %><br>
  <%= f.text_field :genre %>
  <%= f.label :genre %><br>
  <%= f.text_field :image %>
  <%= f.label :image %><br>
  <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<div class='form'>
<h1>Edit Book</h1>
<%= render :partial => 'form' %>
</div>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <div class='wrap'>
  <%= link_to image_tag(book.image, :class => 'index'), book %>
  <ul>
    <li><%= book.title %></li>
    <li><%= book.author.name if book.author %></li>
    <li><%= book.year %></li>
    <li><%= book.genre %></li>
  </ul>
  </div>
<% end %>

app/views/books/new.html.erb
<div class='form'>
<h1>New Book</h1>
<%= render :partial => 'form' %>
</div>

app/views/books/show.html.erb
<section>
<%= image_tag @book.image, :class => 'show' %>
<ul>
  <li><%= @book.title %></li>
  <li><%=link_to @book.author.name, author_path(@book.author_id) %></li>
  <li><%= @book.year %></li>
  <li><%= @book.genre %></li>
</ul>
</section>

<div class='links'>
<%= link_to 'Delete', @book, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_book_path(@book) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul>
      <li><%= link_to 'Authors', authors_path %></li>
      <li>/</li>
      <li><%= link_to 'Books', books_path %></li>
      <li>/</li>
      <li><%= link_to 'New Author', new_author_path %></li>
      <li>/</li>
      <li><%= link_to 'New Book', new_book_path %></li>
    </ul>
  </nav>

<%= yield %>

</body>
</html>